### ISSUE TITLE
Getting consistent "Unknown error 523" while trying to access some directories on AZNFS mounts.

### ISSUE THREAD

**Issue by Konstantin-Denin** [Azure/AZNFS-mount#114]
Hello Team!
Azure Support recommended opening this issue with you, so here we are.

1. Issue description: 
As we started using NFS-enabled BLOBs, we noticed that some common OS commands, such as "find", "ls" or "du" return "Unknown error 523" while we access some directories on AZNFS mount points.

2. How to reproduce:
 Example 1:
```
find /mount_point -type d
```
~~~
find: ‘/mount_point/2024-03-13’: Unknown error 523
find: ‘/mount_point/2024-03-15’: Unknown error 523
find: ‘/mount_point/2024-03-16’: Unknown error 523
find: ‘/mount_point/2024-03-17’: Unknown error 523
find: ‘/mount_point/2024-03-18’: Unknown error 523
~~~
Please, notice that there was no error for existing directory "/mount_point/2024-03-14"

 Example 2:
```
du -sh /mount_point/2024-03-16
```
~~~
du: /mount_point/2024-03-16: Unknown error 523
789G /mount_point/2024-03-16
~~~

3. Common patterns noticed:
 1) Issue occurs only on AZNFS mounts: Blobfuse mounts or locally attached disks are not affected;
 2) Issue occurs only against directories - files inside them stay fully accessible: they can be successfully read or written, created of deleted;
 3) Issue doesn't occur against files;
 4) Issue is consistently manifested for same directories;
 5) Issue is consistently manifested for same directories irrespectively of performance load of the mount point.
 6) Not all directories are affected by the issue: as we noticed, the more files a directory contains, the higher chance of the issue - most of directories that contain 1000+ files are most likely affected.
 7) If you remove all files in the affected directory, issue will still exist for it;

4. BLOB consistency:
Issue occurs against various VMs and NFS BLOBs in various Azure regions in various subscriptions - Azure Support specialists didn't find any anomalies in those BLOBs.

5. Workaround (helps for some time, but then issue reoccurs):
 1) Create a new directory; 
 2) Move all files there;
 3) Delete original directory;
 4) Move new directory to old path;

6. Hypothesis: issue might look like a directory metadata corruption on AZNFS mount after certain number of files are created or copied inside.

7. System details:
 1) VM location: MS Azure
 2) Linux version: Oracle Linux Server release 8.9
 3) Kernel major version: 5.4.17-2136 UEK6
 4) Affected AZNFS versions: 2.0.3 / 2.0.4

Best Regards,
Konstantin @ Akamai

**Comment by palashvij-msft** [comment]
Acknowledged @Konstantin-Denin! We are taking a look at the issue.

**Comment by palashvij-msft** [comment]
Hey @Konstantin-Denin,

Could you please reach out to the support team regarding account/container details and the rough timeline when the issue occurred? It's best not to share them here. Once you connect with them, provide the necessary information and ask them to create an incident for us.

Let me know if you face any issues. We'll investigate further.

Thanks,
Palash

**Comment by Konstantin-Denin** [comment]
Hello @palashvij-msft, by the support team, do you mean Azure Support team or any other support team?

**Comment by palashvij-msft** [comment]
@Konstantin-Denin, yes, please contact the Azure support team. To clarify, this issue pertains to the server side and is unrelated to AZNFS. Therefore, it's best to log this as an incident. When reaching out to customer support, kindly request them to create a Sev3 incident and assign it to me (Palash Vij). Also, ensure to share all relevant details with them.

Let me know if you need any further assistance.

Thanks,
Palash

**Comment by palashvij-msft** [comment]
Hey @Konstantin-Denin,

After careful investigation of the case and examination of your scenario resulting in the client throwing error 523 while enumerating a large directory, we've compiled our findings:

The NFS client is sending a cookie verifier that's over a day old to the server. By that time, the server had already purged the cache for that particular cookie verifier. Consequently, the server returns NFS3ERR_BAD_COOKIE, resulting in error 523 in the kernel. Ideally, to handle such bad cookies, the client should make a new call with a zero cookie verifier to obtain a fresh cookie verifier for enumerating the directory anew. However, the client is retrying the same call with the same cookie verifier.

This issue is known in older kernels, including the one you're currently using, _**5.4.17-2136 UEK6**_.

The latest kernel for **_Oracle Linux 8 (>5.15.x)_** addresses this problem by correctly calling the server with a zero cookie verifier for fresh enumeration, as expected.

We recommend upgrading the kernel to the latest version to receive the fix for this issue. This is the most effective way to completely resolve the issue. I'll also 

As a temporary workaround, you can attempt to mitigate the issue by clearing the cache on the client side before launching the application. This ensures that clients discard the old cookie verifier and make new readdir calls with a zero cookie verifier. However, please note that this workaround is not foolproof, as the client remains susceptible to bad cookie errors when the server-side cache is purged. 

**Short term work around:** 
echo 3 > /proc/sys/vm/drop_caches 

Disclaimer: For safety reasons, we strongly advise testing the upgrade on a test virtual machine within the production setup before widely deploying it to production virtual machines. Additionally, please adhere to any other best practices to ensure safety. We cannot be held responsible for any loss or damage incurred.

If you still face any issues even after upgradation, please feel free to reach out! 

Best regards, 
Palash

**Comment by Konstantin-Denin** [comment]
Thank you, @palashvij-msft!
5.15 is in our close plans in another project for this year.
If it also fixes this "Error 523 issue", that would be even better.

I think, we are all clear.
Let's close this issue and have a good day.

Best Regards,
Konstantin
