### ISSUE TITLE
YUM hardcoded in install script causing install to fail on Debian 12

### ISSUE THREAD

**Issue by kanekennedy** [Azure/AZNFS-mount#144]
It looks like Yum has been hardcoded in the script
```
yum="yum"
apt=0
zypper=0
distro_id=
install_cmd=
```

This causes a failure on Debian 12

```
#  wget -O - -q https://github.com/Azure/AZNFS-mount/releases/latest/download/aznfs_install.sh | bash
Retrieving distro info from /etc/os-release...
main: line 187: yum: command not found
[FATAL] Error installing AZNFS version 2.0.9 (Error: 127). See 'yum' command logs above for more information
```

downloading the script and changing the lines to 
```
yum=0
apt=1
zypper=0
distro_id=
install_cmd=
```
allows the script to run.

**Comment by palashvij-msft** [comment]
Hello,

Thank you for highlighting this issue. While our supported distributions may differ from the one you mentioned, you can refer to our list of supported distributions [here](https://github.com/Azure/AZNFS-mount?tab=readme-ov-file#supported-distros). Given this, the installation should have encountered an error due to incompatibility. However, we have addressed this in our latest release, version 2.0.10.

Additionally, for exploratory purposes, we have introduced a new environment variable, AZNFS_FORCE_PACKAGE_MANAGER. This variable accepts values such as apt, yum, dnf, or zypper, allowing users to experiment with different package managers during installation. Please note that this option is solely for academic purposes and does not imply compatibility with unsupported distributions.

Thank you for your feedback and for helping us improve.

Best regards
